version: "3.8"

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    extra_hosts:
     - "host.docker.internal:host-gateway"
    volumes:
     - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
     - ./grafana/dashboards:/var/lib/grafana/dashboards
     - 'grafana_storage:/var/lib/grafana'

  db:
    image: postgres:13
    command: ["postgres", "-c", "fsync=0", "-c", "full_page_writes=off", "-c", "bgwriter_lru_maxpages=0", "-c", "synchronous_commit=off", "-c", "log_statement=all", "-c", "wal_level=logical"]
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
      - ./schemes/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=12345

  weather-handler:
    build:
      context: ./weather-api
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"

volumes:
  postgres-db-data:
  grafana_storage: 
