version: "3.8"

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    environment:
    - "GF_INSTALL_PLUGINS=marcusolsson-json-datasource"
    - "GF_AUTH_DISABLE_LOGIN_FORM=true"
    - "GF_AUTH_ANONYMOUS_ENABLED=true"
    volumes:
     - ./grafana/dashboards:/var/lib/grafana/dashboards
     - ./grafana/provisioning:/etc/grafana/provisioning
     - grafana-storage:/var/lib/grafana
    networks:
     - grafana-network

  db:
    image: postgres:13
    container_name: pg-db
    command: ["postgres", "-c", "fsync=0", "-c", "full_page_writes=off", "-c", "bgwriter_lru_maxpages=0", "-c", "synchronous_commit=off", "-c", "log_statement=all", "-c", "wal_level=logical"]
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
      - ./schemes/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=12345

  weather-service:
    build:
      context: ./weather-api
      dockerfile: deployments/Dockerfile
    container_name: weather-service
    ports:
      - "8080:8080"
    networks:
     - grafana-network

volumes:
  postgres-db-data:
  grafana-storage: 

networks:
  grafana-network:
    driver: bridge
    external: false
